version: "2.4"

x-roslog-environment: &roslog-environment
  ROS_PYTHON_LOG_CONFIG_FILE: /python_logging.conf
  ROSCONSOLE_CONFIG_FILE: /cpp_logging.conf
  ROSCONSOLE_FORMAT: "${X_ROSCONSOLE_FORMAT:-${node}}/${X_ROSCONSOLE_FORMAT:-${logger}} [${X_ROSCONSOLE_FORMAT:-${severity}}] ${X_ROSCONSOLE_FORMAT:-${message}}"

x-logging:
  &default-logging
  driver: "journald"
  options:
    tag: "{{.Name}}/{{.ID}}"

services:
  vx300s:
    build: ./vx300s
    depends_on:
      - ros_master
    network_mode: "host"
    privileged: true
    environment:
      <<: *roslog-environment
      PYTHONUNBUFFERED: 1
      DISPLAY: ${DISPLAY}
      LIBGL_ALWAYS_INDIRECT: 0
    volumes:
      - type: bind
        source: /dev
        target: /dev
        read_only: true
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "~/.Xauthority:/root/.Xauthority"
      - "./config/ros_python_logging.conf:/python_logging.conf:ro"
      - "./config/ros_cpp_logging.conf:/cpp_logging.conf:ro"
      - "./config/perception:/root/interbotix_ws/src/interbotix_ros_manipulators/interbotix_ros_xsarms/interbotix_xsarm_perception/config/:rw"
      - "./config/urdf:/root/interbotix_ws/src/interbotix_ros_manipulators/interbotix_ros_xsarms/interbotix_xsarm_descriptions/urdf:ro"
      - "./config/control:/app/config/control:ro"
      - "./vx300s/docker-entrypoint.sh:/app/docker-entrypoint.sh:ro"
      - "./vx300s/jupyter-lab.sh:/app/jupyter-lab.sh:ro"
      - "./vx300s/scripts:/app/scripts:ro"
      - "./jupyter:/jupyter:rw"
      - "./vx300s/arm_apps/:/root/interbotix_ws/src/arm_apps/:rw"
      - "./config/rviz:/root/interbotix_ws/src/arm_apps/arm_ctrl_rviz/rviz/:rw"
    logging: *default-logging
    command: ["use_original_rviz:=false", "use_sim:=true"]

  camera:
    build: ./camera
    depends_on:
      - ros_master
    network_mode: "host"
    environment:
      <<: *roslog-environment
      PYTHONUNBUFFERED: 1
    privileged: true
    volumes:
      - type: bind
        source: /dev
        target: /dev
        read_only: true
      - "./config/ros_python_logging.conf:/python_logging.conf:ro"
      - "./config/ros_cpp_logging.conf:/cpp_logging.conf:ro"
    logging: *default-logging

  ros_master:
    image: ros:noetic-ros-core
    hostname: localhost
    command: stdbuf -o L roscore
    restart: always
    network_mode: "host"
    logging: *default-logging
